### PR TITLE
Adding features

### PR DESCRIPTION
**Pull request by KCNilssen**
This adds extra functions under the extra_features that builds upon the original statsapi.
Would this then be merged with the statsapi upon completion of necessary functions or leave separate?
 
A readme has been attached within extra_functions to familiarize the user with the usage

### CODE REVIEW

**Comment by Mattsface** [comment]
Nice! This looks like this could make a great CLI tool, or least let you flex the API and other python functions.

This is what I think, and let me know your thoughts. 

1. Let's leave the calling of the MLB Stats API and classes to this repository.
2. Create a new repository (mlb-cli whatever name you want)
3. Create a CLI tool with the functionality of sorting and presenting the data to the User.

Thoughts? 
This reminds me a lot of a project I did a long time ago: https://github.com/Mattsface/xenapi-admin-tools-py

I'm doing the same thing using the XenAPI python library to retrieve the information I want and then doing some stuff and presenting it to the user.

This will get you familiar with the API until we are ready for more complicated stuff :)

**Comment by KCNilssen** [comment]
The extra_features added in this commit not a CLI Tool. The MLB Stats API has a few functions defined in statsapi/__init__.py that take the outputs from the api calls and present meaningful data to the user. The function I wrote is just expanding on this. Take a look at line 209 boxscore() and line 446 boxscore_data(). The two functions liveGames
liveGames_data are similar in design and achive the same goals. liveGames_data() gets the data and then liveGames is just to pretty print that data out. 

The calls made to the actual mlb api is done with the get() function in that same file based on what endpoints is used the make the call. If you wanted to only leave this for strictly accessing the mlb api, you would just remove those functions and keep the get() functions.

**Comment by Mattsface** [comment]
Are you talking about these functions @knilssen? https://github.com/zero-sum-seattle/zero-sum-mlb-statsAPI/blob/master/statsapi/__init__.py#L209-L814

**Comment by Mattsface** [comment]
I can't find the liveGames_data functions. Can you link me?

**Comment by Mattsface** [comment]
I can't find the liveGames_data functions. Can you link me? @KCNilssen

**Comment by KCNilssen** [comment]
@Mattsface https://github.com/zero-sum-seattle/zero-sum-mlb-statsAPI/blob/adding_features/extra_features/__init__.py

**Comment by Mattsface** [comment]
Oh my mistake. I thought you were printing. Let's merge these for now. However, I will make a CLI tool as I need something to test the Jenkins pipeline. You are more than welcome to help :)

**Review by Mattsface — APPROVED** [review]

**Pull request merged**
